export const languagesList = {
  af: { name: "Afrikaans" },

  sq: { name: "Albański" },

  am: { name: "amharski" },

  ar: { name: "arabski" },

  hy: { name: "ormiański" },

  az: { name: "Azerbejdżan" },

  bj: { name: "Bajan" },

  rm: { name: "bałkański" },

  eu: { name: "baskijski" },
  bn: { name: "bengalski" },
  be: { name: "Białoruś" },
  bi: { name: "Bislama" },
  bs: { name: "bośniacki" },
  br: { name: "Breton" },
  bg: { name: "bułgarski" },
  my: { name: "birmański" },
  ca: { name: "Kataloński" },
  cb: { name: "Cebuano" },
  ch: { name: "Chamorro" },
  zh: { name: "chiński" },
  zd: { name: "Komorczyk" },
  co: { name: "koptyjski" },
  ba: { name: "kreolski" },
  hr: { name: "Chorwacki" },
  cs: { name: "Czeski" },
  da: { name: "Duński" },
  nl: { name: "holenderski" },
  dz: { name: "Dzongkha" },
  en: { name: "angielski" },
  eo: { name: "Esperanto" },
  et: { name: "estoński" },
  fn: { name: "Fanagalo" },
  fo: { name: "farerski" },
  fi: { name: "fiński" },
  fr: { name: "francuski" },
  gl: { name: "Galicyjski" },
  ka: { name: "gruziński" },
  de: { name: "niemiecki" },
  el: { name: "grecki" },
  gr: { name: "grecki" },
  gu: { name: "gudżarati" },
  ha: { name: "Hausa" },
  ha: { name: "hawajski" },
  on: { name: "hebrajski" },
  hi: { name: "Hindi" },
  hu: { name: "węgierski" },
  is: { name: "islandzki" },
  id: { name: "indonezyjski" },
  kl: { name: "Inuktitut" },
  ga: { name: "irlandzko-gaelicki" },
  it: { name: "włoski" },
  ja: { name: "japoński" },
  jv: { name: "Jawajski" },
  ke: { name: "Kabuverdianu" },
  ka: { name: "Kabylian" },
  kn: { name: "Kannada" },
  kk: { name: "kazachski" },
  km: { name: "Khmer" },
  rw: { name: "Kinyarwanda" },
  rn: { name: "Kirundi" },
  ko: { name: "koreański" },
  ku: { name: "kurdyjski" },
  ky: { name: "Kirgiski" },
  lo: { name: "Lao" },
  la: { name: "łac." },
  lv: { name: "łotewski" },
  lt: { name: "litewski" },
  lb: { name: "luksemburska" },
  mk: { name: "macedoński" },
  mg: { name: "malgaski" },
  ms: { name: "malajski" },
  dv: { name: "Maledivian" },
  mt: { name: "Maltańczyk" },
  gv: { name: "Manx-gaelicki" },
  mi: { name: "Maorysi" },
  mh: { name: "Marszałek" },
  ja: { name: "Mende" },
  mn: { name: "mongolski" },
  mf: { name: "Morisyen" },
  ne: { name: "Nepalski" },
  ni: { name: "Niuean" },
  nr: { name: "Norweski" },
  ny: { name: "Nyanja" },
  ur: { name: "Pakistańczyk" },
  pa: { name: "Palauan" },
  pa: { name: "Panjabi" },
  pa: { name: "Papiamentu" },
  ps: { name: "Paszto" },
  fa: { name: "perski" },
  pi: { name: "Pijin" },
  pl: { name: "polski" },
  pt: { name: "portugalski" },
  po: { name: "Potawatomi" },
  qu: { name: "Keczua" },
  ru: { name: "rosyjski" },
  sm: { name: "Samoan" },
  sg: { name: "Sango" },
  gd: { name: "Szkoci" },
  sr: { name: "serbski" },
  sn: { name: "Szona" },
  si: { name: "syngaleski" },
  sk: { name: "słowacki" },
  sl: { name: "słoweński" },
  st: { name: "Sotho" },
  es: { name: "hiszpański" },
  sr: { name: "Sranan" },
  sw: { name: "suahili" },
  sv: { name: "szwedzki" },
  de: { name: "niemiecki" },
  sy: { name: "syryjski" },
  tl: { name: "tagalski" },
  tg: { name: "tadżycki" },
  tm: { name: "Tamaszek" },
  ta: { name: "Tamilski" },
  te: { name: "Telugu" },
  te: { name: "Tetum" },
  th: { name: "tajski" },
  bo: { name: "tybetański" },
  ti: { name: "Tigrinia" },
  tp: { name: "Tok-Pisin" },
  tk: { name: "Tokelauan" },
  do: { name: "Tonga" },
  tn: { name: "Tswana" },
  tr: { name: "turecki" },
  tk: { name: "Turkmen" },
  tv: { name: "Tuvaluan" },
  uk: { name: "ukraiński" },
  pp: { name: "Uma" },
  uz: { name: "Uzbecki" },
  vi: { name: "wietnamski" },
  wl: { name: "Wallisian" },
  cy: { name: "Walijski" },
  wo: { name: "Wolof" },
  xh: { name: "Xhosa" },
  yi: { name: "jidysz" },
  zu: { name: "Zulu" },

  // af: { name: "Afrikaans" },

  // sq: { name: "Albanian" },

  // am: { name: "Amharic" },

  // ar: { name: "Arabic" },

  // hy: { name: "Armenian" },

  // az: { name: "Azerbaijani" },

  // bj: { name: "Bajan" },

  // rm: { name: "Balkan-Gipsy" },

  // eu: { name: "Basque" },

  // be: { name: "Bemba" },
  // bn: { name: "Bengali" },
  // be: { name: "Bielarus" },
  // bi: { name: "Bislama" },
  // bs: { name: "Bosnian" },
  // br: { name: "Breton" },
  // bg: { name: "Bulgarian" },
  // my: { name: "Burmese" },
  // ca: { name: "Catalan" },
  // cb: { name: "Cebuano" },
  // ch: { name: "Chamorro" },
  // zh: { name: "Chinese" },
  // zd: { name: "Comorian" },
  // co: { name: "Coptic" },
  // ba: { name: "Creole" },
  // hr: { name: "Croatian" },
  // cs: { name: "Czech" },
  // da: { name: "Danish" },
  // nl: { name: "Dutch" },
  // dz: { name: "Dzongkha" },
  // en: { name: "English" },
  // eo: { name: "Esperanto" },
  // et: { name: "Estonian" },
  // fn: { name: "Fanagalo" },
  // fo: { name: "Faroese" },
  // fi: { name: "Finnish" },
  // fr: { name: "French" },
  // gl: { name: "Galician" },
  // ka: { name: "Georgian" },
  // de: { name: "German" },
  // el: { name: "Greek" },
  // gr: { name: "Greek" },
  // gu: { name: "Gujarati" },
  // ha: { name: "Hausa" },
  // ha: { name: "Hawaiian" },
  // he: { name: "Hebrew" },
  // hi: { name: "Hindi" },
  // hu: { name: "Hungarian" },
  // is: { name: "Icelandic" },
  // id: { name: "Indonesian" },
  // kl: { name: "Inuktitut" },
  // ga: { name: "Irish-Gaelic" },
  // it: { name: "Italian" },
  // ja: { name: "Japanese" },
  // jv: { name: "Javanese" },
  // ke: { name: "Kabuverdianu" },
  // ka: { name: "Kabylian" },
  // kn: { name: "Kannada" },
  // kk: { name: "Kazakh" },
  // km: { name: "Khmer" },
  // rw: { name: "Kinyarwanda" },
  // rn: { name: "Kirundi" },
  // ko: { name: "Korean" },
  // ku: { name: "Kurdish" },
  // ky: { name: "Kyrgyz" },
  // lo: { name: "Lao" },
  // la: { name: "Latin" },
  // lv: { name: "Latvian" },
  // lt: { name: "Lithuanian" },
  // lb: { name: "Luxembourgish" },
  // mk: { name: "Macedonian" },
  // mg: { name: "Malagasy" },
  // ms: { name: "Malay" },
  // dv: { name: "Maldivian" },
  // mt: { name: "Maltese" },
  // gv: { name: "Manx-Gaelic" },
  // mi: { name: "Maori" },
  // mh: { name: "Marshallese" },
  // me: { name: "Mende" },
  // mn: { name: "Mongolian" },
  // mf: { name: "Morisyen" },
  // ne: { name: "Nepali" },
  // ni: { name: "Niuean" },
  // no: { name: "Norwegian" },
  // ny: { name: "Nyanja" },
  // ur: { name: "Pakistani" },
  // pa: { name: "Palauan" },
  // pa: { name: "Panjabi" },
  // pa: { name: "Papiamentu" },
  // ps: { name: "Pashto" },
  // fa: { name: "Persian" },
  // pi: { name: "Pijin" },
  // pl: { name: "Polish" },
  // pt: { name: "Portuguese" },
  // po: { name: "Potawatomi" },
  // qu: { name: "Quechua" },
  // ru: { name: "Russian" },
  // sm: { name: "Samoan" },
  // sg: { name: "Sango" },
  // gd: { name: "Scots" },
  // sr: { name: "Serbian" },
  // sn: { name: "Shona" },
  // si: { name: "Sinhala" },
  // sk: { name: "Slovak" },
  // sl: { name: "Slovenian" },
  // so: { name: "Somali" },
  // st: { name: "Sotho" },
  // es: { name: "Spanish" },
  // sr: { name: "Sranan" },
  // sw: { name: "Swahili" },
  // sv: { name: "Swedish" },
  // de: { name: "German" },
  // sy: { name: "Syriac" },
  // tl: { name: "Tagalog" },
  // tg: { name: "Tajik" },
  // tm: { name: "Tamashek" },
  // ta: { name: "Tamil" },
  // te: { name: "Telugu" },
  // te: { name: "Tetum" },
  // th: { name: "Thai" },
  // bo: { name: "Tibetan" },
  // ti: { name: "Tigrinya" },
  // tp: { name: "Tok-Pisin" },
  // tk: { name: "Tokelauan" },
  // to: { name: "Tongan" },
  // tn: { name: "Tswana" },
  // tr: { name: "Turkish" },
  // tk: { name: "Turkmen" },
  // tv: { name: "Tuvaluan" },
  // uk: { name: "Ukrainian" },
  // pp: { name: "Uma" },
  // uz: { name: "Uzbek" },
  // vi: { name: "Vietnamese" },
  // wl: { name: "Wallisian" },
  // cy: { name: "Welsh" },
  // wo: { name: "Wolof" },
  // xh: { name: "Xhosa" },
  // yi: { name: "Yiddish" },
  // zu: { name: "Zulu" },
};
